/** Expense categories offered in the form, most frequent first. */
export const expenseCategories = [
  'Loyer',
  'Électricité',
  'Eau',
  'Internet',
  'Téléphone',
  'Salaire',
  'Prime',
  'Transport',
  'Livraison',
  'Carburant',
  'Manutention',
  'Emballage',
  'Sacs',
  'Cintres',
  'Nettoyage',
  'Réparations',
  'Fournitures',
  'Publicité Facebook / Instagram / TikTok',
  'Influenceurs',
  'Frais bancaires',
  'Frais Mobile Money',
  'Taxes / frais administratifs',
  'Autre',
]
