import { FormEvent, ReactNode, useEffect, useState } from 'react'
import type { Session } from '@supabase/supabase-js'
import { supabase } from '../lib/supabase'
import { desktopAuthRedirect, isTauriApp, listenForDesktopOAuth, openOAuthInSystemBrowser } from '../lib/desktopAuth'
import { Eye,EyeOff } from 'lucide-react'

type Shop={id:string;name:string;city:string|null;country:string|null;currency:string}
export function AuthGate({children,onSimulation}:{children:(shop:Shop,signOut:()=>Promise<void>,updateShop:(shop:Shop)=>void)=>ReactNode;onSimulation:()=>void}){
 const[session,setSession]=useState<Session|null>(null),[shop,setShop]=useState<Shop|null>(null),[loading,setLoading]=useState(true),[mode,setMode]=useState<'login'|'signup'>('login'),[message,setMessage]=useState(''),[showPassword,setShowPassword]=useState(false)
 useEffect(()=>{let dispose:()=>void=()=>{};let active=true;void listenForDesktopOAuth(message=>setMessage(message)).then(unlisten=>{if(active)dispose=unlisten;else unlisten()}).catch(()=>setMessage('Impossible d’initialiser le retour de connexion.'));return()=>{active=false;dispose()}},[])
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[])
 useEffect(()=>{if(!session){setShop(null);setLoading(false);return}setLoading(true);supabase.from('shops').select('id,name,city,country,currency').limit(1).maybeSingle().then(({data,error})=>{if(error)setMessage('Impossible de charger votre commerce. Vérifiez votre connexion puis réessayez.');setShop(data as Shop|null);setLoading(false)})},[session])
 function authError(error:unknown){const m=String((error as any)?.message||'').toLowerCase();if(m.includes('invalid login')||m.includes('invalid credentials'))return 'Adresse e-mail ou mot de passe incorrect.';if(m.includes('email not confirmed'))return 'Confirmez votre adresse e-mail avant de vous connecter.';if(m.includes('already registered')||m.includes('already been registered'))return 'Un compte existe déjà avec cette adresse e-mail.';if(m.includes('password'))return 'Le mot de passe doit contenir au moins 6 caractères.';if(m.includes('network')||m.includes('fetch'))return 'Connexion impossible. Vérifiez Internet puis réessayez.';return 'Une erreur est survenue. Vérifiez les informations puis réessayez.'}
 async function auth(e:FormEvent<HTMLFormElement>){e.preventDefault();setMessage('');const f=new FormData(e.currentTarget),email=String(f.get('email')).trim(),password=String(f.get('password'));const r=mode==='login'?await supabase.auth.signInWithPassword({email,password}):await supabase.auth.signUp({email,password});if(r.error)setMessage(authError(r.error));else if(mode==='signup'&&!r.data.session)setMessage('Compte créé. Vérifiez votre e-mail pour confirmer votre inscription.')}
 async function googleAuth(){setMessage('');const desktop=isTauriApp();const{data,error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:desktop?desktopAuthRedirect():window.location.origin,skipBrowserRedirect:desktop}});if(error){setMessage(authError(error));return}if(desktop&&data.url){try{await openOAuthInSystemBrowser(data.url)}catch(e){setMessage((e as Error).message||'Impossible d’ouvrir le navigateur pour continuer la connexion.')}}}
 async function createShop(e:FormEvent<HTMLFormElement>){e.preventDefault();setMessage('');const f=new FormData(e.currentTarget);const{data,error}=await supabase.rpc('create_my_shop',{p_name:String(f.get('name')),p_city:String(f.get('city')||''),p_country:String(f.get('country')||'Congo'),p_currency:'XAF'});if(error)setMessage(authError(error));else setShop(data as Shop)}
 if(loading)return <div className="authshell"><div className="authcard"><h1>COVI</h1><p>Chargement de votre commerce…</p></div></div>
 if(!session)return <div className="authshell"><form className="authcard" onSubmit={auth}><div className="authlogo">C<span>O</span>VI</div><h1>{mode==='login'?'Bienvenue sur COVI':'Créer mon compte'}</h1><p>Le système d’exploitation de votre commerce.</p><label>E-mail<input name="email" type="email" required autoComplete="email"/></label><label>Mot de passe<div className="passwordfield"><input name="password" type={showPassword?'text':'password'} minLength={6} required autoComplete={mode==='login'?'current-password':'new-password'}/><button type="button" className="passwordeye" aria-label={showPassword?'Masquer le mot de passe':'Afficher le mot de passe'} onClick={()=>setShowPassword(!showPassword)}>{showPassword?<EyeOff/>:<Eye/>}</button></div></label>{message&&<p className="authmessage">{message}</p>}<button className="primary" type="submit">{mode==='login'?'Se connecter':'Créer mon compte'}</button><div className="authdivider"><span>ou</span></div><button className="googleauth" type="button" onClick={googleAuth}><span className="googlemark">G</span>Continuer avec Google</button><button className="authswitch" type="button" onClick={()=>{setMode(mode==='login'?'signup':'login');setMessage('')}}>{mode==='login'?'Première fois ? Créer un compte':'J’ai déjà un compte'}</button>{mode==='login'&&<button className="demo-link" type="button" onClick={onSimulation}>Découvrir COVI avec une simulation de 3 mois</button>}</form></div>
 if(!shop)return <div className="authshell"><form className="authcard" onSubmit={createShop}><div className="authlogo">C<span>O</span>VI</div><h1>Créons votre commerce</h1><p>Ces informations personnaliseront votre espace COVI.</p><label>Nom de la boutique<input name="name" required placeholder="Ex. Boutique Élégance"/></label><label>Ville<input name="city" placeholder="Ex. Brazzaville"/></label><label>Pays<input name="country" defaultValue="Congo"/></label>{message&&<p className="authmessage">{message}</p>}<button className="primary" type="submit">Créer mon commerce</button></form></div>
 return <>{children(shop,async()=>{await supabase.auth.signOut()},setShop)}</>
}
