import React,{useState} from 'react';import{createRoot}from'react-dom/client';import{Home,ShoppingCart,Package,Ship,Boxes,History,ReceiptText,ChartNoAxesCombined,Settings,Plus,Search,Menu,ArrowUpRight,WalletCards,ChevronRight}from'lucide-react';import'./styles.css';

const money=(n:number)=>new Intl.NumberFormat('fr-FR').format(n)+' FCFA';
const nav=[['Tableau de bord',Home],['Nouvelle vente',ShoppingCart],['Mon stock',Package],['Mes arrivages',Ship],['Mes commandes',Boxes],['Mes ballons',Boxes],['Produits vendus',History],['Charges de la boutique',ReceiptText],['Statistiques',ChartNoAxesCombined],['Paramètres',Settings]] as const;
const products=[['Robe longue wax','Vêtement','35 000 FCFA','1 pièce'],['Jean bleu premium','Vêtement','22 500 FCFA','12 pièces'],['Chemise Zara','Vêtement','18 000 FCFA','1 pièce'],['Sac à main','Accessoire','28 000 FCFA','6 pièces']];
function Brand(){return <div className="brand"><span>C</span><b>O</b><span>VI</span><i></i></div>}
function Dashboard({go}:{go:(s:string)=>void}){return <><div className="hello"><div><p>Dimanche 5 octobre</p><h1>Bonsoir 👋</h1><span>Voici l'essentiel de votre commerce.</span></div><button onClick={()=>go('Nouvelle vente')}><Plus/> Nouvelle vente</button></div><div className="kpis"><Kpi t="Ventes aujourd’hui" v={money(186500)} s="8 ventes"/><Kpi t="Ventes ce mois" v={money(2840000)} s="+12% vs mois dernier"/><Kpi t="Bénéfice estimé" v={money(736000)} s="Après charges"/><Kpi t="Stock disponible" v="284" s="articles"/></div><div className="grid"><section className="card big"><div className="cardhead"><div><small>ACTIVITÉ</small><h2>Ventes de la semaine</h2></div><b>{money(812000)}</b></div><div className="bars">{[42,68,53,83,72,95,62].map((h,i)=><div className="barwrap" key={i}><div className="bar" style={{height:h+'%'}}></div><span>{['L','M','M','J','V','S','D'][i]}</span></div>)}</div></section><section className="card"><small>ARRIVAGES</small><h2>À suivre</h2><Arrival title="Commande #0048" sub="Chine · Guangzhou Fashion" value="815 000 FCFA" status="Reçue"/><Arrival title="Ballon #002" sub="Friperie · Europe" value="83% récupéré" status="En cours"/><button className="link" onClick={()=>go('Mes arrivages')}>Voir mes arrivages <ChevronRight/></button></section></div><div className="grid"><section className="card"><small>BÉNÉFICE</small><h2>Ce mois-ci</h2><div className="profit"><span>Ventes encaissées <b>{money(2840000)}</b></span><span>Coût des arrivages <b>- {money(1680000)}</b></span><span>Charges de la boutique <b>- {money(424000)}</b></span><strong>Bénéfice final estimé <em>{money(736000)}</em></strong></div></section><section className="card"><small>RACCOURCIS</small><h2>Actions rapides</h2><div className="quick"><button onClick={()=>go('Nouvelle vente')}><ShoppingCart/>Vendre</button><button onClick={()=>go('Mon stock')}><Plus/>Ajouter un produit</button><button onClick={()=>go('Mes arrivages')}><Ship/>Nouvel arrivage</button></div></section></div></>}
function Kpi({t,v,s}:{t:string,v:string,s:string}){return <div className="kpi"><span>{t}</span><b>{v}</b><small>{s}</small></div>}
function Arrival({title,sub,value,status}:{title:string,sub:string,value:string,status:string}){return <div className="arrival"><div><b>{title}</b><span>{sub}</span></div><div className="right"><b>{value}</b><small>{status}</small></div></div>}
function Stock(){return <Page title="Mon stock" sub="Tout ce qui est disponible à la vente." action="+ Ajouter un produit"><div className="search"><Search/><input placeholder="Rechercher un produit, une marque, une catégorie…"/></div><div className="table">{products.map((p,i)=><div className="row" key={i}><div className="thumb">{p[0][0]}</div><div className="grow"><b>{p[0]}</b><span>{p[1]}</span></div><b>{p[2]}</b><span className="qty">{p[3]}</span><ChevronRight/></div>)}</div></Page>}
function Arrivages(){return <Page title="Mes arrivages" sub="Suivez tout ce qui entre dans votre commerce." action="+ Nouvel arrivage"><div className="choice"><article><div className="ico"><Boxes/></div><small>FOURNISSEUR</small><h2>Commande fournisseur</h2><p>Produits commandés en Chine, Inde, Turquie, Dubaï ou ailleurs. Gérez fournisseur, transport, douane et quantités.</p><button>Créer une commande <ArrowUpRight/></button></article><article><div className="ico"><Package/></div><small>LOT MIXTE</small><h2>Ballon</h2><p>Enregistrez le coût global puis découvrez et ajoutez les pièces progressivement à l'ouverture du ballon.</p><button>Ajouter un ballon <ArrowUpRight/></button></article></div><div className="card"><small>DERNIERS ARRIVAGES</small><Arrival title="CMD-0048" sub="Chine · 65 articles" value="815 000 FCFA" status="Reçue"/><Arrival title="BAL-003" sub="Europe · 74 pièces enregistrées" value="+138 000 FCFA" status="Rentabilisé"/></div></Page>}
function Sale(){return <Page title="Nouvelle vente" sub="Une vente doit pouvoir être enregistrée en quelques secondes."><div className="sale"><section className="card"><div className="search"><Search/><input placeholder="Rechercher un article…"/></div>{products.slice(0,3).map((p,i)=><div className="row" key={i}><div className="thumb">{p[0][0]}</div><div className="grow"><b>{p[0]}</b><span>{p[2]}</span></div><button className="add">+</button></div>)}</section><section className="card checkout"><small>VENTE EN COURS</small><h2>Panier vide</h2><p>Sélectionnez un article pour commencer.</p><div className="total"><span>Total</span><b>0 FCFA</b></div><button className="primary">Valider la vente</button></section></div></Page>}
function Page({title,sub,action,children}:{title:string,sub:string,action?:string,children:React.ReactNode}){return <><div className="hello"><div><h1>{title}</h1><span>{sub}</span></div>{action&&<button><Plus/>{action.replace('+ ','')}</button>}</div>{children}</>}
function Placeholder({name}:{name:string}){return <Page title={name} sub="Cette section fait partie du socle COVI V1."><div className="empty"><div className="ico"><Package/></div><h2>{name}</h2><p>L'écran est en place. Nous détaillerons son parcours et ses composants métier dans la prochaine passe.</p></div></Page>}
function App(){const[page,setPage]=useState('Tableau de bord');const[open,setOpen]=useState(false);let content=page==='Tableau de bord'?<Dashboard go={setPage}/>:page==='Mon stock'?<Stock/>:page==='Mes arrivages'?<Arrivages/>:page==='Nouvelle vente'?<Sale/>:<Placeholder name={page}/>;return <div className="app"><aside className={open?'open':''}><Brand/><p className="tag">Le système d’exploitation<br/>de votre commerce.</p><nav>{nav.map(([n,I])=><button className={page===n?'active':''} onClick={()=>{setPage(n);setOpen(false)}} key={n}><I/>{n}</button>)}</nav><div className="shop"><span>MA BOUTIQUE</span><b>Boutique Démo</b><small>Brazzaville · XAF</small></div></aside><main><header><button className="menub" onClick={()=>setOpen(!open)}><Menu/></button><div className="mobilebrand"><Brand/></div><div className="sync">● Synchronisé</div><div className="avatar">RB</div></header><div className="content">{content}</div></main><div className="bottom">{[['Accueil',Home,'Tableau de bord'],['Vendre',ShoppingCart,'Nouvelle vente'],['Stock',Package,'Mon stock'],['Plus',Menu,'Mes arrivages']].map(([n,I,p]:any)=><button className={page===p?'active':''} onClick={()=>setPage(p)} key={n}><I/>{n}</button>)}</div></div>}createRoot(document.getElementById('root')!).render(<App/>);